# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d7a9d3a8f9599c5f7b7f6e57fea90e3a3db9d215ad92a126855c788d2efd83a6ca9ebf437f71599a837989b9bbc4f0e1fab7e7ce2ddfc63f4c977e06d37bab9

test:
  secret_key_base: d049b09d3e416db2d2d154c39daebe7bc559476d1eace2d5a581fb47b74adff0004927dc8e3565c2b177c46330ac8052b9ff22bf7464bbf9628ffbe30e51a0a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
